name: user_repositories
description: All repositories in points dealing directly with users, for finding and fetching users,
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  supabase: ^0.3.6

dev_dependencies:
  test: ^1.19.3

  # Mocking and faking
  faker: ^2.0.0

  # Helpers
  auth_repository:
    path: ../auth_repository
  hive_test:
    path: ../hive_test
